  [[main]]
  name = "About Me"
  weight = 200
  identifier = "home"
  url = "/"

  [[main]]
  name = "Research"
  identifier = "research"
  weight = 300
  url = "/research/"

  [[main]]
  name = "Poetry"
  weight = 400
  identifier = "poetry"
  url = "/poetry/"

  [[main]]
  name = "Science"
  weight = 500
  identifier = "science"
  url = "/science/"

  [[main]]
  name = "Misc"
  weight = 500
  identifier = "misc"
  url = "/misc/"

  